<h1>Identificador automático de idioma</h1>
<p><b>Problema</b>: Dados um texto de entrada, é possível identificar em qual língua o texto está escrito?</p>
<p>
Entrada: "texto qualquer" <br />
Saída: português ou inglês ou francês ou italiano ou...
</p>
<p>&nbsp;</p>

<h2>O processo de Reconhecimento de Padrões</h2>
<p>O objetivo desse trabalho é demonstrar o processo de "construção de atributos" e como ele é fundamental para o <b>Reconhecimento de Padrões (RP)</b>.</p>

<p>Primeiro um conjunto de "amostras" previamente conhecido (classificado)</p>

In [2]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

A "amostras" de texto precisa ser "transformada" em <b>padrões</b>

<p>Um padrão é um conjunto de características, geralmente representado por um vetor e um conjunto de padrões no formato de tabela. Onde cada linha é um padrão e as colunas as características e, geralmente, na última coluna a <b>classe</b></p>

In [3]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[["I'm planning a vacation.", 'inglês'], ['Quero aprender a tocar violão.', 'português'], ['Hoje é meu aniversário!', 'português'], ["I'm going to the movies tonight.", 'inglês'], ['Estoy emocionado por el concierto.', 'espanhol'], ['Estoy estudiando para mis exámenes.', 'espanhol'], ['Vamos ao cinema no sábado.', 'português'], ['I want to learn French.', 'inglês'], ['I like listening to music.', 'inglês'], ["Let's go for a walk.", 'inglês'], ['¡Que tengas un buen día!', 'espanhol'], ['Preciso fazer exercícios físicos regularmente.', 'português'], ['What is your favorite color?', 'inglês'], ['Adoro explorar novos lugares.', 'português'], ['This is a beautiful place.', 'inglês'], ['Estoy planeando unas vacaciones.', 'espanhol'], ["I'm studying for my exams.", 'inglês'], ['¿Dónde puedo encontrar un taxi?', 'espanhol'], ['Preciso resolver esse problema o mais rápido possível.', 'português'], ["I'm learning to play the guitar.", 'inglês'], ['O trânsito está terrível hoje.', 'português'], [

O DataFrame do pandas facilita a visualização.

In [4]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

0          1
0               I'm planning a vacation.     inglês
1         Quero aprender a tocar violão.  português
2                Hoje é meu aniversário!  português
3       I'm going to the movies tonight.     inglês
4     Estoy emocionado por el concierto.   espanhol
..                                   ...        ...
87            Can you help me with this?     inglês
88      Necesito comprar algunas frutas.   espanhol
89  O filme que assisti ontem foi ótimo.  português
90      I'm sorry for the inconvenience.     inglês
91                 Vamos a dar un paseo.   espanhol

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [ ]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

def listaPalavras(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  palavras = [s for s in palavras if len(s)>0]
  #uma lista com palavras sem espaços
  return palavras

def somaCaracteres(palavras):
  soma = 0
  for p in palavras:
    soma=soma+p
  return soma

def tamanhoMedioFrases(texto):
  
  return somaCaracteres(texto) / len(listaPalavras)


def contaEspeciais(frase):
    especiais = 'çãõáàâéêíóôúüñ'
    conta_especiais = sum(frase.count(c) for c in especiais)
    proporcao_especiais = conta_especiais / somaCaracteres(frase)
    #print(f'Proporção de caracteres especiais: {proporcao_especiais:.2f}')
    return proporcao_especiais

def bigramas(texto):
    # Bigramas comuns em cada idioma
  bigramas_pt = ['ão', 'nh', 'lh', 'os', 'as']
  bigramas_es = ['ll', 'rr', 'ch', 'de', 'la']
  bigramas_en = ['th', 'he', 'in', 'er', 'an']
  frase = listaPalavras(texto)
  
  total_bigramas_frase = 0
  for palavra in frase:
    total_bigramas_frase += len(palavra) - 1 if len(palavra) > 1 else 1
    if bigramas_pt:
       bgPt += 1
    if bigramas_es:
       bgEs += 1 
    if bigramas_en:
       bgEn += 1
  



def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=contaEspeciais(texto)
  caracteristica3=funcao2(texto)
  # acrescente as suas funcoes no vetor padrao
  padrao = [caracteristica1, caracteristica2, caracteristica3, frase[1] ]
  return padrao


def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

[[3.8, 0, 0, 'inglês'], [5.0, 0, 0, 'português'], [4.75, 0, 0, 'português'], [3.5714285714285716, 0, 0, 'inglês'], [5.8, 0, 0, 'espanhol'], [6.0, 0, 0, 'espanhol'], [4.2, 0, 0, 'português'], [3.6, 0, 0, 'inglês'], [4.2, 0, 0, 'inglês'], [2.3333333333333335, 0, 0, 'inglês'], [3.6, 0, 0, 'espanhol'], [8.2, 0, 0, 'português'], [4.6, 0, 0, 'inglês'], [6.25, 0, 0, 'português'], [4.2, 0, 0, 'inglês'], [7.0, 0, 0, 'espanhol'], [3.3333333333333335, 0, 0, 'inglês'], [5.0, 0, 0, 'espanhol'], [5.75, 0, 0, 'português'], [3.5714285714285716, 0, 0, 'inglês'], [5.0, 0, 0, 'português'], [4.5, 0, 0, 'português'], [4.25, 0, 0, 'inglês'], [6.2, 0, 0, 'português'], [7.8, 0, 0, 'espanhol'], [7.333333333333333, 0, 0, 'espanhol'], [4.2, 0, 0, 'inglês'], [4.5, 0, 0, 'português'], [3.3333333333333335, 0, 0, 'espanhol'], [3.2, 0, 0, 'inglês'], [5.4, 0, 0, 'inglês'], [5.833333333333333, 0, 0, 'português'], [5.166666666666667, 0, 0, 'português'], [3.8333333333333335, 0, 0, 'espanhol'], [5.333333333333333, 0, 0, '

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:27: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:27: SyntaxWarning: invalid escape sequence '\w'
C:\Users\trabalho\AppData\Local\Temp\ipykernel_18168\3320403498.py:5: SyntaxWarning: invalid escape sequence '\s'
  palavras = re.split("\s",texto)
C:\Users\trabalho\AppData\Local\Temp\ipykernel_18168\3320403498.py:27: SyntaxWarning: invalid escape sequence '\w'
  pattern_regex = re.compile('[^\w+]', re.UNICODE)


0  1  2          3
0   3.800000  0  0     inglês
1   5.000000  0  0  português
2   4.750000  0  0  português
3   3.571429  0  0     inglês
4   5.800000  0  0   espanhol
..       ... .. ..        ...
87  3.333333  0  0     inglês
88  7.000000  0  0   espanhol
89  4.142857  0  0  português
90  4.333333  0  0     inglês
91  3.200000  0  0   espanhol

[92 rows x 4 columns]

<h2>Treinando o modelo com SVM</h1>
<p>Separando o conjunto de treinamento do conjunto de testes</p>

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


Com os conjuntos separados, podemos "treinar" o modelo usando a SVM.

In [35]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 53.42%
[[ 0  9 15]
 [ 0 19  5]
 [ 0  5 20]]
              precision    recall  f1-score   support

    espanhol       0.00      0.00      0.00        24
      inglês       0.58      0.79      0.67        24
   português       0.50      0.80      0.62        25

    accuracy                           0.53        73
   macro avg       0.36      0.53      0.43        73
weighted avg       0.36      0.53      0.43        73

métricas mais confiáveis
[[0 2 4]
 [0 6 0]
 [0 2 5]]
              precision    recall  f1-score   support

    espanhol       0.00      0.00      0.00         6
      inglês       0.60      1.00      0.75         6
   português       0.56      0.71      0.63         7

    accuracy                           0.58        19
   macro avg       0.39      0.57      0.46        19
weighted avg       0.39      0.58      0.47        19



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classif